### ISSUE TITLE
I met this error when run python3 demo.py 

### ISSUE THREAD

**Issue by bemoregt** [akanimax/BMSG-GAN#22]
Hi, @markstrefford @owang @sridharmahadevan @akanimax @huangzh13 

I met this error when run python3 demo.py 

tezro@sgi320:~/deepZ/BMSG-GAN/sourcecode$ python3 demo.py --generator_file ./GAN_GEN_60.pth 
Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    from generate_multi_scale_samples import progressive_upscaling
  File "/home/tezro/deepZ/BMSG-GAN/sourcecode/generate_multi_scale_samples.py", line 9, in <module>
    from torchvision.utils import make_grid
  File "/usr/local/lib/python3.7/dist-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/rpn.py", line 8, in <module>
    from . import _utils as det_utils
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/detection/_utils.py", line 74, in <module>
    @torch.jit.script
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 364, in script
    graph = _script_graph(fn, _frames_up=_frames_up + 1)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py", line 359, in _script_graph
    ast = get_jit_ast(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 132, in get_jit_ast
    return build_def(SourceRangeFactory(source), py_ast.body[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 151, in build_def
    build_stmts(ctx, body))
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 123, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 123, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 205, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 314, in build_Call
    func = build_expr(ctx, expr.func)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 300, in build_Attribute
    value = build_expr(ctx, expr.value)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/frontend.py", line 422, in build_Subscript
    raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
        proposals (Tensor): boxes to be encoded

What's wrong to me ??

Best,
@bemoregt.

**Comment by akanimax** [comment]
Is this solved by now? I believe it is related to using wrong version of `Python 3` and `Pytorch`. The code uses `Python 3.5` and `PyTorch 1.0.0`
Closing this for now...
